alter table public.usuarios add column if not exists email text;

update public.usuarios u
set email = au.email
from auth.users au
where au.id = u.auth_id and u.email is null;

create unique index if not exists usuarios_academia_email_uidx
on public.usuarios (academia_id, lower(email))
where email is not null;

create table if not exists public.locais (
  id bigint generated by default as identity primary key,
  academia_id bigint not null references public.academias(id) on delete cascade,
  nome text not null,
  token_qr uuid not null default gen_random_uuid(),
  ativo boolean not null default true,
  created_at timestamptz not null default now(),
  unique (academia_id, nome),
  unique (token_qr)
);

alter table public.turmas
  add column if not exists codigo_convite text,
  add column if not exists local_id bigint references public.locais(id) on delete set null;

update public.turmas
set codigo_convite = 'DT-' || upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 8))
where codigo_convite is null;

create unique index if not exists turmas_codigo_convite_uidx
on public.turmas (upper(codigo_convite))
where codigo_convite is not null;

insert into public.locais (academia_id, nome)
select distinct t.academia_id, 'Magnólia'
from public.turmas t
where t.nome ilike 'Magnólia%' and t.academia_id is not null
on conflict (academia_id, nome) do nothing;

insert into public.locais (academia_id, nome)
select distinct t.academia_id, 'Thai Fight'
from public.turmas t
where t.nome ilike 'Thai Fight%' and t.academia_id is not null
on conflict (academia_id, nome) do nothing;

insert into public.locais (academia_id, nome)
select distinct t.academia_id, 'Cubango'
from public.turmas t
where t.nome ilike 'Cubango%' and t.academia_id is not null
on conflict (academia_id, nome) do nothing;

update public.turmas t
set local_id = l.id
from public.locais l
where l.academia_id = t.academia_id
  and (
    (t.nome ilike 'Magnólia%' and l.nome = 'Magnólia')
    or (t.nome ilike 'Thai Fight%' and l.nome = 'Thai Fight')
    or (t.nome ilike 'Cubango%' and l.nome = 'Cubango')
  )
  and t.local_id is null;

create table if not exists public.turma_horarios (
  id bigint generated by default as identity primary key,
  turma_id bigint not null references public.turmas(id) on delete cascade,
  dia_semana smallint not null check (dia_semana between 0 and 6),
  horario_inicio time not null,
  created_at timestamptz not null default now(),
  unique (turma_id, dia_semana, horario_inicio)
);

insert into public.turma_horarios (turma_id, dia_semana, horario_inicio)
select t.id, d.dia, time '20:00'
from public.turmas t
cross join (values (1::smallint), (3::smallint), (5::smallint)) d(dia)
where t.nome = 'Magnólia Adulto'
on conflict do nothing;

insert into public.turma_horarios (turma_id, dia_semana, horario_inicio)
select t.id, d.dia, h.hora
from public.turmas t
cross join (values (1::smallint), (3::smallint), (5::smallint)) d(dia)
cross join (values (time '08:00'), (time '09:00'), (time '10:00')) h(hora)
where t.nome = 'Thai Fight Adulto'
on conflict do nothing;

create table if not exists public.turma_professores (
  turma_id bigint not null references public.turmas(id) on delete cascade,
  usuario_id uuid not null references public.usuarios(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (turma_id, usuario_id)
);

alter table public.chamadas
add column if not exists horario_id bigint references public.turma_horarios(id) on delete set null;

create unique index if not exists chamadas_turma_data_horario_uidx
on public.chamadas (turma_id, data, horario_id)
where horario_id is not null;

create table if not exists public.checkins (
  id bigint generated by default as identity primary key,
  aluno_id bigint not null references public.alunos(id) on delete cascade,
  turma_id bigint not null references public.turmas(id) on delete cascade,
  local_id bigint not null references public.locais(id) on delete cascade,
  horario_id bigint not null references public.turma_horarios(id) on delete cascade,
  aula_data date not null,
  created_at timestamptz not null default now(),
  unique (aluno_id, horario_id, aula_data)
);

create index if not exists locais_academia_id_idx on public.locais(academia_id);
create index if not exists turmas_local_id_idx on public.turmas(local_id);
create index if not exists turma_horarios_turma_id_idx on public.turma_horarios(turma_id);
create index if not exists turma_professores_usuario_id_idx on public.turma_professores(usuario_id);
create index if not exists checkins_aluno_id_idx on public.checkins(aluno_id);
create index if not exists checkins_turma_id_idx on public.checkins(turma_id);

create or replace function private.professor_da_turma(p_turma_id bigint)
returns boolean
language sql stable security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.turma_professores tp
    join public.usuarios u on u.id = tp.usuario_id
    where tp.turma_id = p_turma_id
      and u.auth_id = (select auth.uid())
      and u.cargo = 'Professor'
      and u.status = 'Ativo'
  );
$$;

create or replace function public.validar_codigo_turma(p_codigo text)
returns table (turma_id bigint, turma_nome text, academia_nome text)
language sql stable security definer
set search_path = ''
as $$
  select t.id, t.nome, a.nome
  from public.turmas t
  join public.academias a on a.id = t.academia_id
  where upper(t.codigo_convite) = upper(trim(p_codigo))
    and a.status = 'Ativa'
  limit 1;
$$;

revoke all on function public.validar_codigo_turma(text) from public;
grant execute on function public.validar_codigo_turma(text) to anon, authenticated;

create or replace function public.handle_new_auth_user()
returns trigger
language plpgsql security definer
set search_path = ''
as $$
declare
  v_academia_id bigint;
  v_nome text;
  v_cpf text;
  v_telefone text;
  v_codigo_turma text;
  v_turma_id bigint;
  v_aluno_id bigint;
begin
  v_nome := nullif(trim(coalesce(new.raw_user_meta_data ->> 'nome', '')), '');
  v_cpf := nullif(trim(coalesce(new.raw_user_meta_data ->> 'cpf', '')), '');
  v_telefone := nullif(trim(coalesce(new.raw_user_meta_data ->> 'telefone', '')), '');

  if new.invited_at is not null then
    begin
      v_academia_id := (new.raw_user_meta_data ->> 'academia_id')::bigint;
    exception when others then
      v_academia_id := null;
    end;

    if v_nome is null then
      v_nome := split_part(coalesce(new.email, 'Professor'), '@', 1);
    end if;

    if v_academia_id is null or not exists (
      select 1 from public.academias a
      where a.id = v_academia_id and a.status = 'Ativa'
    ) then
      raise exception 'Academia inválida para convite de professor';
    end if;

    insert into public.usuarios (
      auth_id, nome, email, cargo, telefone, cpf, status, academia_id, aluno_id
    )
    values (
      new.id, v_nome, lower(new.email), 'Professor', v_telefone, v_cpf,
      'Ativo', v_academia_id, null
    )
    on conflict (auth_id) do nothing;

    return new;
  end if;

  v_codigo_turma := nullif(trim(coalesce(new.raw_user_meta_data ->> 'codigo_turma', '')), '');

  if v_nome is null then raise exception 'Nome obrigatório para criar perfil'; end if;
  if v_codigo_turma is null then raise exception 'Código da turma obrigatório'; end if;

  select t.id, t.academia_id
  into v_turma_id, v_academia_id
  from public.turmas t
  join public.academias a on a.id = t.academia_id
  where upper(t.codigo_convite) = upper(v_codigo_turma)
    and a.status = 'Ativa'
  limit 1;

  if v_turma_id is null or v_academia_id is null then
    raise exception 'Código da turma inválido';
  end if;

  if v_cpf is not null then
    select a.id into v_aluno_id
    from public.alunos a
    where a.academia_id = v_academia_id
      and regexp_replace(coalesce(a.cpf, ''), '\D', '', 'g')
          = regexp_replace(v_cpf, '\D', '', 'g')
      and not exists (select 1 from public.usuarios u where u.aluno_id = a.id)
    limit 1;
  end if;

  if v_aluno_id is null then
    insert into public.alunos (
      nome, cpf, telefone, faixa, graus, categoria, status, academia_id
    )
    values (
      v_nome, v_cpf, v_telefone, 'Branca', 0, 'Adulto', 'Ativo', v_academia_id
    )
    returning id into v_aluno_id;
  else
    update public.alunos
    set nome = v_nome,
        cpf = coalesce(v_cpf, cpf),
        telefone = coalesce(v_telefone, telefone)
    where id = v_aluno_id;
  end if;

  insert into public.usuarios (
    auth_id, nome, email, cargo, telefone, cpf, status, academia_id, aluno_id
  )
  values (
    new.id, v_nome, lower(new.email), 'Aluno', v_telefone, v_cpf,
    'Ativo', v_academia_id, v_aluno_id
  )
  on conflict (auth_id) do nothing;

  insert into public.matriculas (aluno_id, turma_id)
  values (v_aluno_id, v_turma_id)
  on conflict (aluno_id, turma_id) do nothing;

  return new;
end;
$$;

create or replace function public.registrar_checkin(p_token text)
returns table (status text, mensagem text, turma_nome text, horario text)
language plpgsql security definer
set search_path = ''
as $$
declare
  v_aluno_id bigint;
  v_academia_id bigint;
  v_local_id bigint;
  v_horario_id bigint;
  v_turma_id bigint;
  v_turma_nome text;
  v_horario time;
  v_agora timestamp;
  v_data date;
  v_chamada_id bigint;
  v_inserido bigint;
begin
  if private.current_user_role() <> 'aluno' then
    raise exception 'Check-in disponível apenas para alunos' using errcode = '42501';
  end if;

  v_aluno_id := private.current_aluno_id();
  v_academia_id := private.current_academia_id();

  if v_aluno_id is null or v_academia_id is null then
    raise exception 'Perfil de aluno inválido' using errcode = '42501';
  end if;

  select l.id into v_local_id
  from public.locais l
  where l.token_qr::text = trim(p_token)
    and l.academia_id = v_academia_id
    and l.ativo = true
  limit 1;

  if v_local_id is null then
    return query select 'invalido'::text, 'QR Code inválido para sua academia.'::text, null::text, null::text;
    return;
  end if;

  v_agora := timezone('America/Sao_Paulo', now());
  v_data := v_agora::date;

  select h.id, t.id, t.nome, h.horario_inicio
  into v_horario_id, v_turma_id, v_turma_nome, v_horario
  from public.turma_horarios h
  join public.turmas t on t.id = h.turma_id
  join public.matriculas m on m.turma_id = t.id and m.aluno_id = v_aluno_id
  where t.local_id = v_local_id
    and extract(dow from v_agora)::smallint = h.dia_semana
    and v_agora between
      (v_data + h.horario_inicio - interval '15 minutes')
      and (v_data + h.horario_inicio + interval '60 minutes')
  order by abs(extract(epoch from (v_agora - (v_data + h.horario_inicio))))
  limit 1;

  if v_horario_id is null then
    return query select 'fora_da_janela'::text, 'Não há uma aula sua aberta para check-in neste local agora.'::text, null::text, null::text;
    return;
  end if;

  insert into public.checkins (aluno_id, turma_id, local_id, horario_id, aula_data)
  values (v_aluno_id, v_turma_id, v_local_id, v_horario_id, v_data)
  on conflict (aluno_id, horario_id, aula_data) do nothing
  returning id into v_inserido;

  if v_inserido is null then
    return query select 'ja_registrado'::text, 'Seu check-in desta aula já foi registrado.'::text, v_turma_nome, to_char(v_horario, 'HH24:MI');
    return;
  end if;

  insert into public.chamadas (turma_id, data, horario, professor, horario_id)
  values (v_turma_id, v_data, to_char(v_horario, 'HH24:MI'), 'Check-in', v_horario_id)
  on conflict (turma_id, data, horario_id) where horario_id is not null
  do update set horario = excluded.horario
  returning id into v_chamada_id;

  insert into public.presencas (chamada_id, aluno_id)
  values (v_chamada_id, v_aluno_id)
  on conflict (chamada_id, aluno_id) do nothing;

  return query select 'registrado'::text, 'Check-in realizado com sucesso.'::text, v_turma_nome, to_char(v_horario, 'HH24:MI');
end;
$$;

revoke all on function public.registrar_checkin(text) from public, anon;
grant execute on function public.registrar_checkin(text) to authenticated;

alter table public.locais enable row level security;
alter table public.turma_horarios enable row level security;
alter table public.turma_professores enable row level security;
alter table public.checkins enable row level security;

create policy locais_select_por_papel on public.locais
for select to authenticated
using (
  (private.is_manager() and academia_id = private.current_academia_id())
  or exists (
    select 1 from public.turmas t
    join public.matriculas m on m.turma_id = t.id
    where t.local_id = locais.id and m.aluno_id = private.current_aluno_id()
  )
);

create policy locais_admin_write on public.locais
for all to authenticated
using (private.is_admin() and academia_id = private.current_academia_id())
with check (private.is_admin() and academia_id = private.current_academia_id());

create policy turma_horarios_select_por_papel on public.turma_horarios
for select to authenticated
using (
  private.turma_na_academia(turma_id)
  and (private.is_admin() or private.professor_da_turma(turma_id) or private.aluno_matriculado_na_turma(turma_id))
);

create policy turma_horarios_admin_write on public.turma_horarios
for all to authenticated
using (private.is_admin() and private.turma_na_academia(turma_id))
with check (private.is_admin() and private.turma_na_academia(turma_id));

create policy turma_professores_select_gestao on public.turma_professores
for select to authenticated
using (
  private.is_admin()
  or usuario_id = (
    select u.id from public.usuarios u
    where u.auth_id = (select auth.uid())
    limit 1
  )
);

create policy turma_professores_admin_write on public.turma_professores
for all to authenticated
using (private.is_admin() and private.turma_na_academia(turma_id))
with check (private.is_admin() and private.turma_na_academia(turma_id));

create policy checkins_select_por_papel on public.checkins
for select to authenticated
using (
  aluno_id = private.current_aluno_id()
  or private.is_admin()
  or private.professor_da_turma(turma_id)
);

drop policy if exists "Usuário pode ler o próprio perfil" on public.usuarios;
create policy usuarios_select_por_papel on public.usuarios
for select to authenticated
using (
  auth_id = (select auth.uid())
  or (private.is_admin() and academia_id = private.current_academia_id())
);

drop policy if exists alunos_select_por_papel on public.alunos;
create policy alunos_select_por_papel on public.alunos
for select to authenticated
using (
  id = private.current_aluno_id()
  or (private.is_admin() and academia_id = private.current_academia_id())
  or exists (
    select 1 from public.matriculas m
    where m.aluno_id = alunos.id and private.professor_da_turma(m.turma_id)
  )
);

drop policy if exists alunos_insert_gestao on public.alunos;
drop policy if exists alunos_update_gestao on public.alunos;
drop policy if exists alunos_delete_gestao on public.alunos;
create policy alunos_insert_admin on public.alunos for insert to authenticated
with check (private.is_admin() and academia_id = private.current_academia_id());
create policy alunos_update_admin on public.alunos for update to authenticated
using (private.is_admin() and academia_id = private.current_academia_id())
with check (private.is_admin() and academia_id = private.current_academia_id());
create policy alunos_delete_admin on public.alunos for delete to authenticated
using (private.is_admin() and academia_id = private.current_academia_id());

drop policy if exists turmas_select_por_papel on public.turmas;
create policy turmas_select_por_papel on public.turmas
for select to authenticated
using (
  (private.is_admin() and academia_id = private.current_academia_id())
  or private.professor_da_turma(id)
  or private.aluno_matriculado_na_turma(id)
);

drop policy if exists turmas_insert_gestao on public.turmas;
drop policy if exists turmas_update_gestao on public.turmas;
drop policy if exists turmas_delete_gestao on public.turmas;
create policy turmas_insert_admin on public.turmas for insert to authenticated
with check (private.is_admin() and academia_id = private.current_academia_id());
create policy turmas_update_admin on public.turmas for update to authenticated
using (private.is_admin() and academia_id = private.current_academia_id())
with check (private.is_admin() and academia_id = private.current_academia_id());
create policy turmas_delete_admin on public.turmas for delete to authenticated
using (private.is_admin() and academia_id = private.current_academia_id());

drop policy if exists matriculas_select_por_papel on public.matriculas;
create policy matriculas_select_por_papel on public.matriculas
for select to authenticated
using (
  aluno_id = private.current_aluno_id()
  or (private.is_admin() and private.aluno_na_academia(aluno_id) and private.turma_na_academia(turma_id))
  or private.professor_da_turma(turma_id)
);

drop policy if exists matriculas_insert_gestao on public.matriculas;
drop policy if exists matriculas_update_gestao on public.matriculas;
drop policy if exists matriculas_delete_gestao on public.matriculas;
create policy matriculas_insert_admin on public.matriculas for insert to authenticated
with check (private.is_admin() and private.aluno_na_academia(aluno_id) and private.turma_na_academia(turma_id));
create policy matriculas_update_admin on public.matriculas for update to authenticated
using (private.is_admin() and private.aluno_na_academia(aluno_id) and private.turma_na_academia(turma_id))
with check (private.is_admin() and private.aluno_na_academia(aluno_id) and private.turma_na_academia(turma_id));
create policy matriculas_delete_admin on public.matriculas for delete to authenticated
using (private.is_admin() and private.aluno_na_academia(aluno_id) and private.turma_na_academia(turma_id));

create or replace function public.salvar_aluno_com_matriculas(
  p_aluno_id bigint, p_nome text, p_cpf text, p_telefone text, p_faixa text,
  p_graus integer, p_categoria text, p_status text, p_turma_ids bigint[]
)
returns bigint
language plpgsql security invoker
set search_path = ''
as $$
declare
  v_academia_id bigint;
  v_aluno_id bigint;
  v_turma_ids bigint[] := coalesce(p_turma_ids, '{}'::bigint[]);
begin
  if not private.is_admin() then
    raise exception 'Sem permissão para gerenciar alunos' using errcode = '42501';
  end if;

  v_academia_id := private.current_academia_id();

  if nullif(trim(coalesce(p_nome, '')), '') is null then
    raise exception 'Nome do aluno é obrigatório' using errcode = '22023';
  end if;

  if exists (
    select 1 from unnest(v_turma_ids) selecionada(turma_id)
    where not private.turma_na_academia(selecionada.turma_id)
  ) then
    raise exception 'Uma ou mais turmas não pertencem à academia do usuário' using errcode = '42501';
  end if;

  if p_aluno_id is null then
    insert into public.alunos (nome, cpf, telefone, faixa, graus, categoria, status, academia_id)
    values (
      trim(p_nome), nullif(trim(coalesce(p_cpf, '')), ''), nullif(trim(coalesce(p_telefone, '')), ''),
      p_faixa, p_graus, p_categoria, p_status, v_academia_id
    )
    returning id into v_aluno_id;
  else
    update public.alunos
    set nome = trim(p_nome), cpf = nullif(trim(coalesce(p_cpf, '')), ''),
        telefone = nullif(trim(coalesce(p_telefone, '')), ''), faixa = p_faixa,
        graus = p_graus, categoria = p_categoria, status = p_status
    where id = p_aluno_id and academia_id = v_academia_id
    returning id into v_aluno_id;

    if v_aluno_id is null then
      raise exception 'Aluno não encontrado nesta academia' using errcode = 'P0002';
    end if;
  end if;

  delete from public.matriculas
  where aluno_id = v_aluno_id and not (turma_id = any(v_turma_ids));

  insert into public.matriculas (aluno_id, turma_id)
  select v_aluno_id, turma_id
  from (select distinct unnest(v_turma_ids) turma_id) s
  on conflict (aluno_id, turma_id) do nothing;

  return v_aluno_id;
end;
$$;
