-- Grade oficial, locais/endereco e suporte a aula extra.
-- Aplicado em produção como migrations grade_locais_e_aulas_extras + aulas_extras_rls.

alter table public.locais add column if not exists endereco text;

update public.locais set nome='Magnólia', endereco='R. Magnólia Brasil, 18 - Fonseca, Niterói - RJ' where id=1;
update public.locais set nome='CT Thai Fight', endereco='R. Lindolfo Collor, 86 - Raul Veiga, São Gonçalo - RJ' where id=2;
update public.locais set nome='CT Dream Team / Cubango', endereco='Tv. das Crianças, 100 - Viçoso Jardim, Niterói - RJ' where id=3;
update public.locais set nome='Projeto Social Ministério Êxodo', endereco='Rua Justino Cardoso, S/N - Água Mineral, São Gonçalo - RJ' where id=5;

-- Os horários são gerenciados em public.turma_horarios.
-- Professores não são pré-atribuídos; os vínculos serão feitos após cada cadastro.

create table if not exists public.aulas_extras (
  id bigint generated by default as identity primary key,
  academia_id bigint not null references public.academias(id) on delete cascade,
  nome text not null default 'Aula extra',
  local_id bigint not null references public.locais(id) on delete restrict,
  data date not null,
  horario time not null,
  professor_usuario_id uuid not null references public.usuarios(id) on delete restrict,
  professor_nome text not null,
  status text not null default 'Aberta' check (status in ('Aberta','Finalizada','Cancelada')),
  created_at timestamptz not null default now()
);

alter table public.chamadas
  add column if not exists aula_extra_id bigint references public.aulas_extras(id) on delete cascade,
  add column if not exists local_id bigint references public.locais(id) on delete set null;
